inherit_from:
  - .rubocop_todo.yml
  - .rubocop_strict.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
 TargetRubyVersion: 2.7
 NewCops: enable
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'spec/rails_helper.rb'
   - 'spec/spec_helper.rb'

Style/Documentation:
 Enabled: false

Metrics/BlockLength:
 IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50
